In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
from torch.autograd import Variable
import numpy as np
import math,random
import matplotlib.pyplot as plt
%matplotlib inline

<h6>pytorch tensors</h6>
pytorch is built on tensors which are numpy arrays accelerated by the GPU. The tensor operations are 
GPU kernels. To move a tensor onto a GPU, use if <br/>
torch.cuda.is_available():<br/>
    &nbsp;&nbsp;&nbsp;device = torch.device("cuda")<br/>
    &nbsp;&nbsp;&nbsp;y = torch.ones_like(x,device=device)<br/>
    &nbsp;&nbsp;&nbsp;x = x.to(device)<br/>
    &nbsp;&nbsp;&nbsp;z = x + y<br/>
    &nbsp;&nbsp;&nbsp;print(z)<br/>
    &nbsp;&nbsp;&nbsp;print(z.to("cpu",torch.double))<br/>
#
<h6>Variables</h6>
For autodiff wrap tensors in pytorch variables from cs230. Conflicting information, you can add requires_grad to a tensor
but you also need a Variable.grad_fn attribute refrencing a function that has created a Tensor? Could be if a 
tensor has a grad_fn as a result of an operation is is now a Variable? Not clear. An operation on a tensor results 
in a new function object; torch.autograd.Function. 
<h6>Autograd</h6>
Backpropagation in pytorch is defined by defining the function in the forward direction then calling
.backward(). 


In [ ]:
x = torch.ones(100,1, requires_grad=True)
print(x)
print (y.grad_fn,x.grad_fn)
y = (x**3)
print(x.requires_grad,y.requires_grad)

print (y.grad_fn,x.grad_fn)
y.sum().backward()
print(x.grad)

In [ ]:
#autodiff requires the tensor reduce to 1 scalar. The point is the last node
# of the simplest NN has a sum node of all the hideen outputs. Called y=x but is
# really y = sum(x). This is what sum() represents. Sum the outputs of the hidden layer outpts. 

#Else you have to add a gradient to each member of the tensor, dont know how to do yet.

a = torch.randn(2, 2,requires_grad=True)
c = ((a * 3) / (a - 1))
b = (c * c).sum()
print(a.size())
print(b.grad_fn) #should be tensor object here
b.backward() # this is the d(output) step. 
print(a.grad) # this is the da to get d(output)/da


In [ ]:
import torch
x = [0,1]
y = np.array([[1,1]])
print("x:",torch.Tensor([x]))
print("y:",torch.Tensor(y))
a = np.array([[1,1],[2,2],[3,3]])
for x in a:
    print(x)
#this does seem better than a lambda bc less typing. dont need the map or list conversion
b = [torch.Tensor(x) for x in a]
print(b)

In [12]:
import torch 
import torch.nn as nn
import torch.optim as optim
import numpy as np
import torch.nn.functional as F

class Simple(nn.Module):
    def __init__(self):
        super(Simple,self).__init__()
        self.fc = nn.Linear(2,50)
    
    def forward(self,x):
        self.sig = F.sigmoid(self.fc(x))
        return self.sig
    
x = np.array([[0,0],[0,1],[1,0],[1,1]])
output = np.array([[0],[0],[0],[1]])
input = [torch.Tensor(i) for i in x]
target = [torch.Tensor(i) for i in output]
#print(input,target)


net = Simple()
for i,j in enumerate(target,0):
    print(i,j)
    print(input[i])
for i,j in enumerate(input,0):
    print(i,j)
    print (output[i])
# train
import torch.optim as optim
criterion = nn.MSELoss()
optimizer = optim.SGD(net.parameters(),lr=0.1)
for e in range(0,20):
    optimizer.zero_grad()
    for i,j in enumerate(target,0):
        print(i,j)
        print(input[i])
        out_predicted = net(input[i])
        print("out_predicted:",out_predicted,"output:",output[i])
    #
    print(e)
    

0 tensor([ 0.])
tensor([ 0.,  0.])
1 tensor([ 0.])
tensor([ 0.,  1.])
2 tensor([ 0.])
tensor([ 1.,  0.])
3 tensor([ 1.])
tensor([ 1.,  1.])
0 tensor([ 0.,  0.])
[0]
1 tensor([ 0.,  1.])
[0]
2 tensor([ 1.,  0.])
[0]
3 tensor([ 1.,  1.])
[1]
0 tensor([ 0.])
tensor([ 0.,  0.])
out_predicted: tensor([ 0.3697,  0.5838,  0.5559,  0.5496,  0.3727,  0.5691,  0.4510,
         0.5709,  0.4306,  0.4338,  0.5962,  0.3705,  0.4600,  0.6422,
         0.4788,  0.5881,  0.5103,  0.3406,  0.5760,  0.6409,  0.3306,
         0.6316,  0.5582,  0.5234,  0.4473,  0.6008,  0.6341,  0.5435,
         0.5117,  0.4002,  0.4003,  0.4538,  0.3412,  0.3880,  0.6027,
         0.5867,  0.3833,  0.4349,  0.4060,  0.4163,  0.6069,  0.6146,
         0.3696,  0.3378,  0.4214,  0.4518,  0.4526,  0.6540,  0.5634,
         0.4135]) output: [0]
1 tensor([ 0.])
tensor([ 0.,  1.])
out_predicted: tensor([ 0.2354,  0.4421,  0.6888,  0.6131,  0.4981,  0.4655,  0.4545,
         0.7035,  0.5783,  0.3733,  0.5234,  0.3021,  0.4166, 

1 tensor([ 0.])
tensor([ 0.,  1.])
out_predicted: tensor([ 0.2354,  0.4421,  0.6888,  0.6131,  0.4981,  0.4655,  0.4545,
         0.7035,  0.5783,  0.3733,  0.5234,  0.3021,  0.4166,  0.7109,
         0.4305,  0.4334,  0.3460,  0.4900,  0.6147,  0.4983,  0.2491,
         0.5906,  0.4358,  0.4889,  0.3997,  0.5316,  0.5328,  0.6560,
         0.6324,  0.4723,  0.5001,  0.6267,  0.3823,  0.4234,  0.6476,
         0.6804,  0.4242,  0.5848,  0.3817,  0.5268,  0.4788,  0.6864,
         0.3960,  0.3676,  0.4001,  0.2915,  0.4160,  0.5824,  0.4582,
         0.3797]) output: [0]
2 tensor([ 0.])
tensor([ 1.,  0.])
out_predicted: tensor([ 0.2441,  0.6531,  0.6636,  0.6166,  0.3316,  0.4418,  0.4197,
         0.7116,  0.4152,  0.3893,  0.5570,  0.4221,  0.4228,  0.4847,
         0.5746,  0.4832,  0.3796,  0.4799,  0.5492,  0.5856,  0.2606,
         0.6144,  0.5404,  0.3598,  0.3140,  0.4907,  0.7636,  0.5562,
         0.3592,  0.2992,  0.5223,  0.5168,  0.3551,  0.5063,  0.4961,
         0.6604,  

In [ ]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

EPOCHS_TO_TRAIN = 50000

class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(2, 3, True)
        self.fc2 = nn.Linear(3, 1, True)

    def forward(self, x):
        x = F.sigmoid(self.fc1(x))
        x = self.fc2(x)
        return x

net = Net()
inputs = list(map(lambda s: Variable(torch.Tensor([s])), [
    [0, 0],
    [0, 1],
    [1, 0],
    [1, 1]
]))
targets = list(map(lambda s: Variable(torch.Tensor([s])), [
    [0],
    [1],
    [1],
    [0]
]))


criterion = nn.MSELoss()
optimizer = optim.SGD(net.parameters(), lr=0.01)

print("Training loop:")
for idx in range(0, EPOCHS_TO_TRAIN):
    for input, target in zip(inputs, targets):
        optimizer.zero_grad()   # zero the gradient buffers
        output = net(input)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()    # Does the update
    #if idx % 5000 == 0:
        #print("Epoch {: >8} Loss: {}".format(idx, loss.data.numpy()[0]))



print("")
print("Final results:")
for input, target in zip(inputs, targets):
    output = net(input)
    print("Input:[{},{}] Target:[{}] Predicted:[{}] Error:[{}]".format(
        int(input.data.numpy()[0][0]),
        int(input.data.numpy()[0][1]),
        int(target.data.numpy()[0]),
        round(float(output.data.numpy()[0]), 4),
        round(float(abs(target.data.numpy()[0] - output.data.numpy()[0])), 4)
    ))

In [ ]:
#wrong? dont see output change to 1. 
class XOR(nn.Module):
    def __init__(self):
        super(XOR,self).__init__()
        self.fc1 = nn.Linear(2,50)
        self.fc2 = nn.Linear(50,1)
        self.relu1 = nn.ReLU()
        self.relu2 = nn.ReLU()

    def forward(self,x):
        x = self.fc1(x)
        x = self.relu1(x)
        x = self.fc2(x)
        x = self.relu2(x)
        return x

net = XOR()
criterion = nn.MSELoss()
optimizer = optim.SGD(list(net.parameters()), lr=0.001, momentum=0.1)
    
trainingdataX = [[[0.01, 0.01], [0.01, 0.90], [0.90, 0.01], [0.95, 0.95]], [[0.02, 0.03], [0.04, 0.95], [0.97, 0.02], [0.96, 0.95]]]
trainingdataY = [[[0.01], [0.90], [0.90], [0.01]], [[0.04], [0.97], [0.98], [0.1]]]
num_epochs=200
for epochs in range(num_epochs):
    running_loss=0.0
    for i , data in enumerate(trainingdataX,0):
        inputs = data
        labels = trainingdataY[i]
        print("i:",i," data:",data," labels:",labels)
        inputs = Variable(torch.FloatTensor(inputs))
        labels = Variable(torch.FloatTensor(labels))
        print("inputs size:",inputs.size(), "labels.size():",labels.size())
        optimizer.zero_grad()
        outputs = net(inputs)
        loss = criterion(outputs,labels)
        loss.backward()
        optimizer.step()
        running_loss+=loss.data[0]
            
        print ("epochs:",epochs,"loss: ", running_loss,"inputs:",inputs,"outputs:",outputs)
        #running_loss = 0.0
print ("Finished training...")
# this is correct for a prediction? 
print (net(Variable(torch.FloatTensor(trainingdataX[0]))))


<img src="rnn.png">

In [ ]:
import numpy as np
import torch

np.random.seed(2)

T = 20
L = 1000
N = 100

x = np.empty((N, L), 'int64')
x[:] = np.array(range(L)) + np.random.randint(-4 * T, 4 * T, N).reshape(N, 1)
data = np.sin(x / 1.0 / T).astype('float64')
torch.save(data, open('traindata.pt', 'wb'))

In [ ]:


class SineWave(nn.Module):
    def __init__(self):
        super(SineWave,self).__init__()
        self.lstm1 = nn.LSTMCell(1,51)
        self.lstm2 = nn.LSTMCell(51,51)
        self.linear = nn.Linear(51,1)
        
    def forward(self,input,future=0):
        outputs = []
        print('input size:',input.size())
        h_t = torch.zeros(input.size(0), 51,dtype=torch.double )
        c_t = torch.zeros(input.size(0), 51,dtype=torch.double )
        h_t2 = torch.zeros(input.size(0), 51,dtype=torch.double )
        c_t2 = torch.zeros(input.size(0), 51,dtype=torch.double )
        print('h_t',h_t.size())
        print('c_t',c_t.size())
        print('h_t2',h_t2.size())
        print('c_t2',c_t2.size())
        
        for i, input_t in enumerate(input.chunk(input.size(1),dim=1)):
            h_t, c_t = self.lstm1(input_t, (h_t,c_t))
            h_t2, c_t2 = self.lstm2(h_t, (h_t2,c_t2))
            output = self.linear(h_t2)
            outputs += [output]
        for i in range(future):# if we should predict the future
            h_t, c_t = self.lstm1(output, (h_t, c_t))
            h_t2, c_t2 = self.lstm2(h_t, (h_t2, c_t2))
            output = self.linear(h_t2)
            outputs += [output]
        outputs = torch.stack(outputs,1).squeeze(2)
        
        return outputs
       
if __name__ == '__main__':
    data = torch.load('traindata.pt')
    print('after load:',data.shape)
    input = torch.from_numpy(data[3:,:-1])
    target = torch.from_numpy(data[3:,1:])
    test_input = torch.from_numpy(data[:3, :-1])
    test_target = torch.from_numpy(data[:3,1:])
    print('input:',input.size())
    print('target:',target.size())
    print('test_input:',test_input.size())
    print('test_target:',test_target.size())
    
    seq = SineWave()
    seq.double()
    criterion = nn.MSELoss()
    for i in range(15):
        print("i:",i)
        def closure():
            optimizer.zero_grad()
            out = seq(input)
            loss = criterion(out,target)
            print("loss:",loss.item())
            loss.backward()
            return loss
        #predict
        with torch.no_grad():
            future = 1000
            pred = seq(test_input,future=future)
            loss = criterion(pred[:,:-future],test_target)
            print('testloss:',loss.item())
            y = pred.detach().numpy()
    print("y:",y.shape)
    plt.figure(figsize=(30,10))
    plt.title('sine wave')
    plt.xlabel('x')
    plt.ylabel('y')
    plt.xticks(fontsize=20)
    plt.yticks(fontsize=20)
    def draw(yi, color):
        plt.plot(np.arange(input.size(1)), yi[:input.size(1)],color,linewidth=2.0)
        plt.plot(np.arange(input.size(1), input.size(1) + future), yi[input.size(1):], color+":", linewidth=2.0)
    draw(y[0],'r')
    draw(y[1],'g')
    draw(y[2],'b')
    #plt.savefig("predict%d.pdf"%i)
    plt.show()
    plt.close()
        
    

In [ ]:
#rnn attention


In [ ]:
#TRANSFORMER FOR translaton doesnt use attention


In [ ]:
#stack overflow tags

In [ ]:
#text summarization as topics. text summarization in tensorflow blog post
# vs running topic LDA only
# how to develop quality metric? 