<h6>Momentum vs. SGD for optimization</h6>
<img src="mom1.png">

<h6>Numerical Stability for calculating exponent divided by sum of exponents</h6>
https://stackoverflow.com/questions/10278004/how-to-order-this-computation-for-numerical-stability

<p>Do not calculate np.exp(x) directly, subtract x_max first</p>
<p>tmp = np.array([-10**10, 10**10])</p>
<p>tmp_max = tmp.max()</p>
<p>logD = np.log(np.sum(np.exp(tmp-tmp_max))) + tmp_max</p>
<p>log_v = tmp - log_D</p>
<p>v = np.exp(log_v)</p>
<p>>>> v
array([ 0.,  1.])</p>
<p></p>

$log\sum_{k=1}^{training set}exp(tmp-tmp_{max}) + tmp_{max}$

$=log\sum_{k=1}^{training set} \frac{exp(tmp)}{exp(tmp_{max})} + tmp_{max}$

$= log\frac{1}{exp(tmp_{max})} \sum_{k=1}^{training set}exp(tmp) + tmp_{max}$ 

$= log[exp(-tmp_{max}) \sum_{k=1}^{training set} exp(tmp)] + tmp_{max}$

$= logexp(-tmp_{max}) + log\sum_{k=1}^{training set}exp(tmp) + tmp_{max}$

$= -tmp_{max} + log\sum_{k=1}^{training set} exp(tmp) + tmp_{max}$

<p>The above sould reduce to summation exp(tmp)</p>
<p>Below for fraction of exp(tmp)/summation(exp(tmp))</p>
<p>Combine log_v = tmp=log_D and v=exp(log_v)</p>
$v=exp(tmp-logD) = \frac{exp(tmp)}{log_D}$

In [ ]:
Reference: http://cs231n.github.io/linear-classify/#softmax

$\frac{exp(x)}{\sum_{k=1}^{K} exp(x)}$
<p></p>

$\frac{C * exp(x)}{C*\sum_{k=1}^{K}exp(x)}$

$\frac{exp(x + logC)}{\sum_{k=1}^{K}exp(x+logC)}$

In [79]:
import numpy as np
tmp=[1,2,3,4,5,6,7,8]
#tmp = np.array([-10**10, 10**10])
   
def foo(tmp):
    tmp_max=np.max(tmp)
    logD = np.log(np.sum(np.exp(tmp-tmp_max))) + tmp_max
    log_v = tmp - logD
    v = np.exp(log_v)
    return v

print(foo(tmp))


[  5.76612770e-04   1.56739601e-03   4.26062410e-03   1.15815771e-02
   3.14819905e-02   8.55769227e-02   2.32622194e-01   6.32332683e-01]


In [91]:
import numpy as np

def softmax(x):
    """Compute softmax values for each sets of scores in x."""
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis=0)

scores = [30000000000, 50000000000, 70000000000]
print(softmax(scores))

[ 0.  0.  1.]


In [81]:

print (softmax(tmp))

[  5.76612770e-04   1.56739601e-03   4.26062410e-03   1.15815771e-02
   3.14819905e-02   8.55769227e-02   2.32622194e-01   6.32332683e-01]


from scipy.io import loadmat
x = loadmat('data.mat')
print(x)

In [20]:
print(x['data']['training'])

[[ array([[ (array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.01960784],
       ..., 
       [ 0.        ,  0.        ,  0.03921569, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.02352941, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]]), array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]]))]],
      dtype=[('inputs', 'O'), ('targets', 'O')])]]


In [46]:
#print(x['data']['training'])
train = x['data']['training']
print(train)

[[ array([[ (array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.01960784],
       ..., 
       [ 0.        ,  0.        ,  0.03921569, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.02352941, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]]), array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]]))]],
      dtype=[('inputs', 'O'), ('targets', 'O')])]]


In [47]:
print(train.shape)                                                                                                                       
print(train[0,0].shape)
print(train[0][0])

(1, 1)
(1, 1)
[[ (array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.01960784],
       ..., 
       [ 0.        ,  0.        ,  0.03921569, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.02352941, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]]), array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]]))]]


In [21]:
print(x['data']['validation'])

[[ array([[ (array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]]), array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.05882353, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.25490198, ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]]))]],
      dtype=[('targets', 'O'), ('inputs', 'O')])]]


In [22]:
print(x['data']['test'])

[[ array([[ (array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.42745101,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.71372551,  0.01176471, ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.70980394,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.42352945,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]]), array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]]))]],
      dtype=[('inputs', 'O'), ('targets', 'O')])]]


In [48]:
print(x['data']['test'])

[[ array([[ (array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.42745101,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.71372551,  0.01176471, ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.70980394,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.42352945,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]]), array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]]))]],
      dtype=[('inputs', 'O'), ('targets', 'O')])]]


In [51]:
x['data']['test']

array([[ array([[ (array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.42745101,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.71372551,  0.01176471, ...,  0.        ,
         0.        ,  0.        ],
       ..., 
       [ 0.        ,  0.70980394,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.42352945,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ]]), array([[ 1.,  0.,  0., ...,  0.,  0.,  0.],
       [ 0.,  1.,  0., ...,  0.,  0.,  0.],
       [ 0.,  0.,  1., ...,  0.,  0.,  0.],
       ..., 
       [ 0.,  0.,  0., ...,  1.,  0.,  0.],
       [ 0.,  0.,  0., ...,  0.,  1.,  0.],
       [ 0.,  0.,  0., ...,  0.,  0.,  1.]]))]],
      dtype=[('inputs', 'O'), ('targets', 'O')])]], dtype=object)

In [65]:
from scipy.io import loadmat
dt_train_target = loadmat('dt_train_target.mat')
dt_train_input = loadmat('dt_train_input.mat')
dt_test_input = loadmat('dt_test_input.mat')
dt_train_target = loadmat('dt_test_target.mat')
dt_valid_input = loadmat('dt_valid_input.mat')
dt_valid_target = loadmat('dt_valid_target.mat')




dt_train_input.keys()
dt_train_input['dt_train_input'].shape[1]

1000

In [114]:
def a3(wd_coefficient, n_hid,n_iters,learning_rate,momentum_multiplier,do_early_stopping, mini_batch_size):
    model = initial_model(n_hid)
    from_data_file = load('data.mat')
    datas = from_data_file.data
    n_training_cases = dt_train_input['dt_train_input'].shape[1]
    assert(n_training_cases==1000)
    if n_iters !=0:
        test_gradient(model,datas.training,wd_coefficient)

    theta = model_to_theta(model)
    momentum_speed = theta * 0
    training_data_losses = []
    validataion_data_losses = []
    if do_early_stopping:
        best_so_far_theta = -1
        best_so_far_validation_loss = inf
        best_so_far_after_n_iters = -1
    for optimizationn_iteration in range(n_iters):
        model = theta_to_model(theta)
        momentum_speed = theta * 0;
    
        training_batch_start = mod((optimization_iteration_i-1) * mini_batch_size, n_training_cases)+1;
        training_batch.inputs = datas.training.inputs(:, training_batch_start : training_batch_start + mini_batch_size - 1);
        training_batch.targets = datas.training.targets(:, training_batch_start : training_batch_start + mini_batch_size - 1);
        gradient = model_to_theta(d_loss_by_d_model(model, training_batch, wd_coefficient));
        momentum_speed = momentum_speed * momentum_multiplier - gradient;
        theta = theta + momentum_speed * learning_rate;

        model = theta_to_model(theta);
        training_data_losses = [training_data_losses, loss(model, datas.training, wd_coefficient)];
        validation_data_losses = [validation_data_losses, loss(model, datas.validation, wd_coefficient)];
        if do_early_stopping && validation_data_losses(end) < best_so_far.validation_loss,
            best_so_far.theta = theta; % this will be overwritten soon
            best_so_far.validation_loss = validation_data_losses(end);
            best_so_far.after_n_iters = optimization_iteration_i;
        end
        if mod(optimization_iteration_i, round(n_iters/10)) == 0,
          fprintf('After %d optimization iterations, training data loss is %f, and validation data loss is %f\n', optimization_iteration_i, training_data_losses(end), validation_data_losses(end));
        end
    end
  if n_iters ~= 0, test_gradient(model, datas.training, wd_coefficient); end % check again, this time with more typical parameters
  if do_early_stopping:
    fprintf('Early stopping: validation loss was lowest after %d iterations. We chose the model that we had then.\n', best_so_far.after_n_iters);
    theta = best_so_far.theta;
  end

def initial_model(n_hid):
    n_params = 256+10
    #octave starts array indexing from 1, numpy from 0. octave range = n_params-1 and numpy range 0,n_params
    #which is same as range(n_params)
    #the octave code creates a vector from 0 to n_params-1 and does a cos on the range
    #as_row_vector = cos(0:(n_params-1))
    as_row_vector = np.cos(np.array(range(0,n_params)))
    print(as_row_vector.shape)
    #does numpy create transpose also? No, this is tricky, numpy shows a transpose for 2d arrays not 1d
    transpose = np.transpose(np.array(as_row_vector))
    foo =  theta_to_model(transpose * 0.1)
    return foo

#divide into 2 parts, the first 256 and the second 10; the 2 sets of weights are concatenated together
def theta_to_model(theta):
    n_hid = theta.shape[0]
    #lets assume n_hid=1 for now
    input_to_hid = theta[0:256]
    hid_to_class = theta[256:256+10]
    #return a tuple instead of a model object
    return input_to_hid, hid_to_class

def model_to_theta(input_to_hid, hid_to_class):
    return np.stack((input_to_hid, hid_to_class),axis=1)

def logistic(x):
    return 1./(1+np.exp(-x))

#equivalent to log(sum(exp(A)))
def log_sum_exp_over_rows(x):
    #max row similar to octave max(x,[],1) returns max row
    max_row =  np.max(x,axis=0)
    return np.log(np.sum(np.exp(x),axis=0))

A=[[1,2,3],[4,5,6]]
test_logsumexp = log_sum_exp_over_rows(A)
print(type(test_logsumexp))
print(test_logsumexp.shape)
print (test_logsumexp)
foo = np.array([ 4.04858735,  5.04858735,  6.04858735])
print(foo)
#np.testing.assert_array_equal(np.array([1]),np.array([1]))
np.testing.assert_array_equal(test_logsumexp,np.array([ 4.04858735,  5.04858735,  6.04858735]))

<class 'numpy.ndarray'>
(3,)
[ 4.04858735  5.04858735  6.04858735]
[ 4.04858735  5.04858735  6.04858735]


AssertionError: 
Arrays are not equal

(mismatch 100.0%)
 x: array([ 4.048587,  5.048587,  6.048587])
 y: array([ 4.048587,  5.048587,  6.048587])