In [1]:
# Load pickled data
import matplotlib.pyplot as plt
import pickle, cv2, csv, os, time
import numpy as np
from numpy import newaxis
from random import randint
import tensorflow as tf
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
from matplotlib import gridspec
%matplotlib inline
from keras.models import model_from_json
from keras.optimizers import Adam
import copy
from keras.models import Sequential, load_model
from keras.layers.core import Dense, Dropout, Activation, Flatten, Reshape
from keras.optimizers import SGD, RMSprop
from keras.utils import np_utils
from keras.regularizers import l2
from keras.layers.convolutional import Convolution2D, MaxPooling2D, ZeroPadding2D, AveragePooling2D
from keras.callbacks import EarlyStopping
from keras.preprocessing.image import ImageDataGenerator
from keras.layers.normalization import BatchNormalization
from skimage.transform import rescale, resize, downscale_local_mean

from PIL import Image

Using TensorFlow backend.


In [9]:
#for cleanup copying dir to another by accident. copied files from additionalType2 to additionalType1
num_dup=0
for root, dirs, files in os.walk('first1k/', topdown=False):
    for f in files:
        if(os.path.isfile('additional_Type_1_v2//Type_1/'+f)):
            print ('file exists in another dir!!!',f)
            os.remove('additional_Type_1_v2/Type_1/'+f)
            num_dup+=1
print (num_dup)

0


In [10]:


current_path = os.getcwd()
print (current_path)
train_path1 = current_path + "/train/Type_1/"
train_path2 = current_path + "/train/Type_2/"
train_path3 = current_path + "/train/Type_3/"
add_type1 = current_path + "/additional_Type_1_v2/Type_1/" 
add_type2 = current_path + "/additional_Type_2_v2/Type_2/" 
add_type3 = current_path + "/additional_Type_3_v2/Type_3/" 

test = current_path+"/test/"

path_list =[]
path_list.append(add_type1)
path_list.append(add_type2)
path_list.append(add_type3)
path_list.append(train_path1)
path_list.append(train_path2)
path_list.append(train_path3)

path_list.append(test)

 
def resize_images(path,pickle_filename):
    resize_img=[]
    size_dict= {}
    #for path in path_list:
    start_time = time.time()
    for root, dirs, files in os.walk(path, topdown=False):
        print ("path:",path,' numFiles:',len(files))
        for f in files:
            if f !='.DS_Store':
                print ("path:",path," path+f:",path+f)
                img = cv2.imread(path+f)
                print ("img shape:",img.shape)
                image_resize = resize(img, (32, 32), mode='reflect')
                print("img_resize shape:",image_resize.shape)
                resize_img.append(image_resize)
                print("size list:",len(resize_img))                
                size_dict[img.shape[0]]=img.shape[1]
        print("dict of image dimensions:",size_dict)
        with open(pickle_filename,'wb') as save_file:
            pickle.dump(resize_img,save_file)
    end_time = time.time()
    print("elapsed time:",(end_time-start_time)/60.)

#uncomment each one to run. Should run wo memory error. 
#resize_images(train_path1,'type1_resize32.p')
#resize_images(train_path2,'type2resize32.p')
#resize_images(train_path3,'type3resize32.p')
#resize_images(add_type1,'type1addresize32.p')
#resize_images(add_type2,'type2addresize32.p')
resize_images(add_type3,'type3addresize32.p')
#resize_images(test,'test.p')

            

/Users/dc/DeepLearning/kaggle
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  numFiles: 1975
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/100.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1010.jpg
img shape: (4160, 3120, 3)
img_resize shape: (32, 32, 3)
size list: 2
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1012.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 3
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1014.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 4
path: /Users/dc/DeepLearning/kaggle/additional

img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 39
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1150.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 40
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1152.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 41
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1156.jpg
img shape: (2448, 3264, 3)
img_resize shape: (32, 32, 3)
size list: 42
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1160.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 43
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/

img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 78
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1346.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 79
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1356.jpg
img shape: (3096, 4128, 3)
img_resize shape: (32, 32, 3)
size list: 80
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1357.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 81
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1362.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 82
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/

img_resize shape: (32, 32, 3)
size list: 117
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1512.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 118
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1515.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 119
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1519.jpg
img shape: (2448, 3264, 3)
img_resize shape: (32, 32, 3)
size list: 120
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1522.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 121
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle

img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 156
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1669.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 157
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1673.jpg
img shape: (640, 480, 3)
img_resize shape: (32, 32, 3)
size list: 158
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1675.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 159
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1679.jpg
img shape: (640, 480, 3)
img_resize shape: (32, 32, 3)
size list: 160
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users

img shape: (4160, 3120, 3)
img_resize shape: (32, 32, 3)
size list: 195
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1845.jpg
img shape: (640, 480, 3)
img_resize shape: (32, 32, 3)
size list: 196
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1855.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 197
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1860.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 198
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/1866.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 199
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Use

img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 234
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2036.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 235
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/204.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 236
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/205.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 237
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2055.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 238
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Use

img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 273
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2207.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 274
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2211.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 275
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2213.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 276
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2222.jpg
img shape: (640, 480, 3)
img_resize shape: (32, 32, 3)
size list: 277
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Use

img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 312
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2349.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 313
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/235.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 314
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2352.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 315
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/236.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 316
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Use

img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 351
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/256.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 352
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2561.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 353
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2563.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 354
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2568.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 355
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Us

img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 390
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2741.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 391
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2742.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 392
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/275.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 393
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2751.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 394
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Us

img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 429
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2917.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 430
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2927.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 431
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2941.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 432
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/2943.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 433
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /U

img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 468
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3105.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 469
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3107.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 470
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3110.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 471
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3115.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 472
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /U

img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 507
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3262.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 508
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3267.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 509
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3269.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 510
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/327.jpg
img shape: (4160, 3120, 3)
img_resize shape: (32, 32, 3)
size list: 511
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Us

img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 546
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3407.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 547
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3408.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 548
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3410.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 549
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3412.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 550
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /U

img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 585
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3581.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 586
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3585.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 587
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3589.jpg
img shape: (4160, 3120, 3)
img_resize shape: (32, 32, 3)
size list: 588
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/359.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 589
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Us

img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 624
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3759.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 625
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3760.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 626
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3768.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 627
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3769.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 628
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /U

img shape: (4160, 3120, 3)
img_resize shape: (32, 32, 3)
size list: 663
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3928.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 664
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/393.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 665
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3934.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 666
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/3936.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 667
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Us

img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 702
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4100.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 703
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4101.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 704
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4102.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 705
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4103.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 706
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /U

img_resize shape: (32, 32, 3)
size list: 741
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4179.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 742
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4189.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 743
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4190.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 744
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4191.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 745
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle

img_resize shape: (32, 32, 3)
size list: 780
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4302.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 781
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4303.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 782
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4318.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 783
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4324.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 784
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle

img_resize shape: (32, 32, 3)
size list: 819
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4407.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 820
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4408.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 821
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4409.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 822
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/441.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 823
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/

img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 858
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4506.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 859
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4507.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 860
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4508.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 861
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4509.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 862
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /U

img shape: (2448, 3264, 3)
img_resize shape: (32, 32, 3)
size list: 897
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4610.jpg
img shape: (2448, 3264, 3)
img_resize shape: (32, 32, 3)
size list: 898
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4611.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 899
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4612.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 900
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4613.jpg
img shape: (2448, 3264, 3)
img_resize shape: (32, 32, 3)
size list: 901
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /U

img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 936
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4749.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 937
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4750.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 938
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4751.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 939
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4752.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 940
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /U

img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 975
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4798.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 976
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4799.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 977
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4800.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 978
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4801.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 979
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /U

img_resize shape: (32, 32, 3)
size list: 1014
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4852.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1015
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4853.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1016
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4854.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1017
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4855.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1018
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/k

img shape: (4128, 2322, 3)
img_resize shape: (32, 32, 3)
size list: 1053
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4965.jpg
img shape: (4128, 2322, 3)
img_resize shape: (32, 32, 3)
size list: 1054
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4966.jpg
img shape: (4128, 2322, 3)
img_resize shape: (32, 32, 3)
size list: 1055
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4967.jpg
img shape: (4128, 2322, 3)
img_resize shape: (32, 32, 3)
size list: 1056
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/4969.jpg
img shape: (4128, 2322, 3)
img_resize shape: (32, 32, 3)
size list: 1057
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+

img_resize shape: (32, 32, 3)
size list: 1092
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5019.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1093
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5020.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1094
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5021.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1095
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5022.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1096
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/k

img_resize shape: (32, 32, 3)
size list: 1131
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5076.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1132
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5077.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1133
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5078.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1134
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5079.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1135
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/k

img_resize shape: (32, 32, 3)
size list: 1170
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/517.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1171
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5185.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1172
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5186.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1173
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5197.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1174
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/ka

img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1209
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5247.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1210
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5258.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1211
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5259.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1212
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/526.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 1213
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f

img_resize shape: (32, 32, 3)
size list: 1248
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5308.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1249
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5309.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1250
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5310.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1251
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5311.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1252
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/k

img_resize shape: (32, 32, 3)
size list: 1287
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/536.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1288
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5391.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1289
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5392.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1290
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5393.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1291
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/ka

img_resize shape: (32, 32, 3)
size list: 1326
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5437.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1327
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5438.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1328
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5439.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1329
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5440.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1330
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/k

img_resize shape: (32, 32, 3)
size list: 1365
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5489.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1366
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5490.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1367
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5502.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1368
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5503.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1369
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/k

img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1404
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5566.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1405
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5567.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1406
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5568.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1407
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5569.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1408
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+

img_resize shape: (32, 32, 3)
size list: 1443
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5615.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1444
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5616.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1445
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5634.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1446
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5635.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1447
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/k

img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1482
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5692.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1483
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5693.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1484
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5694.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1485
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5695.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1486
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+

img_resize shape: (32, 32, 3)
size list: 1521
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5750.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1522
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5751.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1523
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5752.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1524
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5754.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1525
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/k

img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 1560
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5867.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1561
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5868.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1562
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5869.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1563
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5870.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1564
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+

img_resize shape: (32, 32, 3)
size list: 1599
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5927.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1600
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5928.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1601
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5933.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1602
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/5934.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1603
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/k

img_resize shape: (32, 32, 3)
size list: 1638
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6009.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1639
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6010.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1640
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6011.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1641
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6012.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1642
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/k

img_resize shape: (32, 32, 3)
size list: 1677
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6094.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1678
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6095.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1679
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6109.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1680
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/611.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 1681
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/ka

img_resize shape: (32, 32, 3)
size list: 1716
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/619.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1717
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/62.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1718
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6203.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1719
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6204.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1720
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kagg

img_resize shape: (32, 32, 3)
size list: 1755
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6283.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1756
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6284.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1757
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6285.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1758
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6286.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1759
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/k

img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1794
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6531.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 1795
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6532.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 1796
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6533.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 1797
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6539.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 1798
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+

img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1833
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6679.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1834
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6680.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1835
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6681.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1836
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6682.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1837
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+

img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 1872
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6799.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 1873
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6800.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 1874
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6801.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 1875
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/6805.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 1876
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+

img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 1911
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/740.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1912
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/745.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 1913
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/748.jpg
img shape: (640, 480, 3)
img_resize shape: (32, 32, 3)
size list: 1914
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/756.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1915
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Us

img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 1950
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/890.jpg
img shape: (640, 480, 3)
img_resize shape: (32, 32, 3)
size list: 1951
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/892.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1952
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/893.jpg
img shape: (3264, 2448, 3)
img_resize shape: (32, 32, 3)
size list: 1953
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/899.jpg
img shape: (4128, 3096, 3)
img_resize shape: (32, 32, 3)
size list: 1954
path: /Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/  path+f: /Us

In [11]:
img1 = []
read_file = open('type1_resize32.p', 'rb') 
imgs_type1 = pickle.load( read_file)
img1 += imgs_type1
print("num type1 images(250):", len(imgs_type1)) #should be 250

read_file = open('type1addresize32.p', 'rb') 
imgs_type1 = pickle.load( read_file)
img1 += imgs_type1
print('num type1 additional images(1190):',len(imgs_type1))


print(len(img1))
label_1 = [0]*(len(img1))
print ('sample label for class Type1 should be 0:',label_1[0])
print ('num labels_1:',len(label_1))

num type1 images(250): 250
num type1 additional images(1190): 1190
1440
sample label for class Type1 should be 0: 0
num labels_1: 1440


In [7]:
read_file = open('test.p','rb')
imgs_test = pickle.load(read_file)
print(len(imgs_test))

512


In [ ]:
path = '/Users/dc/DeepLearning/kaggle/additional_Type_2_v2/Type_2/'
path_first='/Users/dc/DeepLearning/kaggle/first1k/'
path_second='/Users/dc/DeepLearning/kaggle/2ndk/'
path_third='/Users/dc/DeepLearning/kaggle/3rdk/'
num=0
for root, dirs, files in os.walk(path):
    for file in files:
        print('moving:',file)
        if (file != '.DS_Store'):
            if (num < 1000):
                os.rename(path+file,path_first+file)
            elif ((num>1000) and (num<2000)):
                os.rename(path+file,path_second+file)
            else:
                os.rename(path+file,path_third+file)
            num+=1
    print('num:',num)

In [ ]:
path_first='/Users/dc/DeepLearning/kaggle/first1k/'
path_second='/Users/dc/DeepLearning/kaggle/2ndk/'
path_third='/Users/dc/DeepLearning/kaggle/3rdk/'

resize_images(path_first,'type2_first.p')
resize_images(path_second,'type2_second.p')
resize_images(path_third,'type2_third.p')


In [ ]:
#redo type 2. Too many files for stupid pickle format

path = '/Users/dc/DeepLearning/kaggle/additional_Type_2_v2'
first1k=[]
second1k=[]
third1k=[]
for file in os.walk(path):
    print (file)
    img = cv2.imread(path+file)
    image_resize = resize(img, (224, 224), mode='reflect')
    if (num < 1000) and (file!='.DS_Store'):
        first1k.append(image_resize)
    else if ((num>1000) and (num<2000)):
        second1k.append(image_resize)
    else:
        thirdk.append(image_resize)
    num+=1


In [15]:
#redo type2

img2 = []

read_file = open('type2resize32.p', 'rb') 
imgs_type2 = pickle.load( read_file)
img2 += imgs_type2
print("num type2_resize:", len(imgs_type2)) #should be 1000-1 for DS_Store

read_file = open('type2addresize32.p', 'rb') 
imgs_type2 = pickle.load( read_file)
img2 += imgs_type2
print("num type2addresize32:", len(imgs_type2)) #should be 1000-1 for DS_Store


#read_file = open('type2_first.p', 'rb') 
#imgs_type2 = pickle.load( read_file)
#img2 += imgs_type2
#print("num type2_first:", len(imgs_type2)) #should be 1000

#read_file = open('type2_second.p', 'rb') 
#imgs_type2 = pickle.load( read_file)
#img2 += imgs_type2
#print("num type2_second:", len(imgs_type2)) #should be 999

#read_file = open('type2_third.p', 'rb') 
#imgs_type2 = pickle.load( read_file)
#img2 += imgs_type2
#print("num type2_third:", len(imgs_type2)) #should be 1566


#label_2=[1]*(781+1000+999+1566)
label_2 = [1]*(len(img2))
print ('label_2:',len(label_2))
print ('sample label for Type2 should be 1:',label_2[0])
print ('num img2:',len(img2))


num type2_resize: 781
num type2addresize32: 3566
label_2: 4347
sample label for Type2 should be 1: 1
num img2: 4347


In [ ]:
# redo type3 move type3 files
path = '/Users/dc/DeepLearning/kaggle/additional_Type_3_v2/Type_3/'
path_first='/Users/dc/DeepLearning/kaggle/first_third1k/'
path_second='/Users/dc/DeepLearning/kaggle/third2ndk/'
#path_third='/Users/dc/DeepLearning/kaggle/third3rdk/'

num = 0

for root, dirs, files in os.walk(path):
    for file in files:
        print('moving:',file)
        if (file != '.DS_Store'):
            if (num < 1000):
                os.rename(path+file,path_first+file)
            elif ((num>1000) and (num<2000)):
                os.rename(path+file,path_second+file)
            else:
                os.rename(path+file,path_third+file)
            num+=1
    print('num:',num)

In [ ]:
path_first='/Users/dc/DeepLearning/kaggle/first_third1k/'
path_second='/Users/dc/DeepLearning/kaggle/third2ndk/'
#path_third='/Users/dc/DeepLearning/kaggle/3rdk/'

resize_images(path_first,'type3_first.p')
resize_images(path_second,'type3_second.p')


In [17]:
img3=[]

read_file = open('type3resize32.p', 'rb') 
imgs_type3 = pickle.load( read_file)
img3 += imgs_type3
print("num type3_resize:", len(imgs_type3)) #should be 

read_file = open('type3addresize32.p', 'rb') 
imgs_type3 = pickle.load( read_file)
img3 += imgs_type3
print("num type3_resize:", len(imgs_type3)) #should be 


#read_file = open('type3_first.p', 'rb') 
#imgs_type3 = pickle.load( read_file)
#img3 += imgs_type3
#print("num type3_first:", len(imgs_type3)) #should be 1000

#read_file = open('type3_second.p', 'rb') 
#imgs_type3 = pickle.load( read_file)
#img3 += imgs_type3
#print("num type3_second:", len(imgs_type3)) #should be 975


print('num img3:',len(img3))
#label_3 = [2]*(450+1000+975)
label_3 = [2]*(len(img3))
print ('len label_3:', len(label_3))
print ('sample label for Type3, should be 2:',label_3[0])

#convert after you mix them up and shuffle
#label_3add = np_utils.to_categorical(label_3add, 3)


num type3_resize: 450
num type3_resize: 1975
num img3: 2425
len label_3: 2425
sample label for Type3, should be 2: 2


In [22]:
#error check
img = img1+img2+img3
label=label_1+label_2+label_3

#save these to verify the labels match the images
with open('img.p','wb') as save_file:
    pickle.dump(img,save_file)
with open('label.p','wb') as save_file:
    pickle.dump(label,save_file)

print(len(img), len(label))
print(type(img),type(label))
X_train = np.array(img)
y_train = np_utils.to_categorical(label, 3)
X_train,y_train=shuffle(X_train,y_train)
print(X_train.shape, y_train.shape)
#change to 25% then split test to test and valid. 
X_train1, X_test1, y_train1, y_test1 = train_test_split(X_train,y_train, test_size=.20, random_state=42)
#X_test2,ytest2,Xvalid2,yvalid2 = train_test_split(X_test1,y_test1,test_size=.5,random_state=42)

#normalize 





8212 8212
<class 'list'> <class 'list'>
(8212, 32, 32, 3) (8212, 3)


In [25]:
print(X_train[0])

[[[ 0.5754902   0.57990196  0.825     ]
  [ 0.60784314  0.52058824  0.86568627]
  [ 0.63186275  0.49264706  0.86127451]
  ..., 
  [ 0.71372549  0.78578431  0.99068627]
  [ 0.91372549  0.99705882  0.98823529]
  [ 0.78431373  1.          0.96470588]]

 [[ 0.50441176  0.36911765  0.83578431]
  [ 0.48970588  0.39558824  0.83872549]
  [ 0.55882353  0.44117647  0.85784314]
  ..., 
  [ 0.72598039  0.56323529  0.92696078]
  [ 0.64313725  0.50980392  0.88235294]
  [ 0.60196078  0.65098039  0.95098039]]

 [[ 0.28333333  0.15686275  0.81470588]
  [ 0.32107843  0.24852941  0.82696078]
  [ 0.45980392  0.34215686  0.84803922]
  ..., 
  [ 0.70637255  0.5495098   0.92205882]
  [ 0.5995098   0.41911765  0.85833333]
  [ 0.52598039  0.38382353  0.82107843]]

 ..., 
 [[ 0.45735294  0.40735294  0.85686275]
  [ 0.46519608  0.3745098   0.73627451]
  [ 0.53088235  0.47598039  0.75833333]
  ..., 
  [ 0.4745098   0.36372549  0.78333333]
  [ 0.48578431  0.36813725  0.77205882]
  [ 0.47794118  0.36029412  0.77990

In [4]:
X_test = np.array(imgs_test)

In [5]:
print(X_test.shape)

(512, 224, 224, 3)


In [10]:
asdf=np_utils.to_categorical(y_train,3)
asdf[0]

array([ 0.,  1.,  0.])

In [7]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras import backend as K
from keras.preprocessing.image import ImageDataGenerator


print (K.image_data_format())

model = Sequential()
model.add(Conv2D(32, (3, 3), input_shape=( 150, 150,3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))

model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Flatten())  # this converts our 3D feature maps to 1D feature vectors
model.add(Dense(64))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(1))
model.add(Activation('sigmoid'))

channels_last


In [ ]:
model.compile(loss='binary_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [ ]:
import os,random


def move_file(source_path,dest_path):
    """
    input: source path, dest path
    output: move 20 percent files from source path to dest path
    """
    list_files = os.listdir(source_path)
    print (len(list_files))

    num_moved=0
    for x in range(1,int(.20*len(list_files))):
        index = random.randint(1, len(list_files))
        print(index,list_files[index])
        source_file = source_path+list_files[index]
        if(os.path.isfile(source_file)):
            dest_file = dest_path+list_files[index]
            os.rename(source_file,dest_file)
            num_moved+=1

    print (num_moved)

#move_file(os.getcwd()+"/data/train/type1/",os.getcwd()+"/data/valid/type1/")
#move_file(os.getcwd()+"/data/train/type2/",os.getcwd()+"/data/valid/type2/")
move_file(os.getcwd()+"/data/train/type3/",os.getcwd()+"/data/valid/type3/")


In [23]:
import os
from keras.models import load_model
from keras.models import Sequential
from keras.layers import Dense, Activation, Dropout,Convolution2D,MaxPooling2D,Flatten
from keras.optimizers import Adam


# number of classes
nb_classes = 3

# input image dimensions
img_rows, img_cols,img_ch = 32, 32, 3

# number of convolutional filters to use
nb_filter1 = 32
nb_filter2 = 64
nb_filter3 = 128



model = Sequential()
model.add(Convolution2D(32, kernel_size=(3, 3),padding='same',
                        input_shape=(img_rows,img_cols,img_ch),name='conv1'))
model.add(Activation('relu',name='relu1'))
model.add(MaxPooling2D(pool_size=(2,2),strides=1,name='maxpool1'))
model.add(Convolution2D(64, kernel_size=(3, 3),padding='same',
                        name='conv2'))
model.add(Activation('relu',name='relu2'))
model.add(MaxPooling2D(pool_size=(2,2),strides=None,name='maxpool2'))
model.add(Convolution2D(128, kernel_size=(3, 3), padding='same',
                        name='conv3'))
model.add(Activation('relu',name='relu3'))
model.add(MaxPooling2D(pool_size=(2,2),strides=None,name='maxpool3'))
model.add(Flatten(name='flatten'))
model.add(Dropout(0.5,name='dropout1'))
model.add(Dense(128, name='hidden1'))
model.add(Activation('relu',name='relu4'))
model.add(Dropout(0.5,name='dropout2'))
model.add(Dense(128,  name='hidden2'))
model.add(Activation('relu',name='relu5'))
model.add(Dense(nb_classes, name='output'))
model.add(Activation('softmax',name='softmax'))

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1 (Conv2D)               (None, 32, 32, 32)        896       
_________________________________________________________________
relu1 (Activation)           (None, 32, 32, 32)        0         
_________________________________________________________________
maxpool1 (MaxPooling2D)      (None, 31, 31, 32)        0         
_________________________________________________________________
conv2 (Conv2D)               (None, 31, 31, 64)        18496     
_________________________________________________________________
relu2 (Activation)           (None, 31, 31, 64)        0         
_________________________________________________________________
maxpool2 (MaxPooling2D)      (None, 15, 15, 64)        0         
_________________________________________________________________
conv3 (Conv2D)               (None, 15, 15, 128)       73856     
__________

In [24]:
import time
nb_epoch = 1000
batch_size=100

model_name='test.chkpt'

if os.path.isfile(model_name):
    try:
        model = load_model(model_name)
        print('loading trained model ...')
    except Exception as e:
        print('Unable to load model', model_name, ':', e)
        raise    


adam = Adam(lr=1e-4, beta_1=0.9, beta_2=0.999, epsilon=1e-08, decay=0.0)
model.compile(optimizer=adam,
          loss='categorical_crossentropy',
          metrics=['accuracy'])

startTime = time.time()
history = model.fit(X_train1, y_train1,
                    batch_size=batch_size, epochs=nb_epoch,
                    verbose=2, validation_data=(X_test1, y_test1))

endTime = time.time()
print('elapsed secs:', (endTime - startTime)/1000.)
#nvidia-smi to see power stats nvidia-smi -i 3 -l -q -d

Train on 6569 samples, validate on 1643 samples
Epoch 1/1000
33s - loss: 1.0164 - acc: 0.5191 - val_loss: 0.9860 - val_acc: 0.5405
Epoch 2/1000
35s - loss: 1.0049 - acc: 0.5264 - val_loss: 0.9780 - val_acc: 0.5405
Epoch 3/1000
35s - loss: 0.9946 - acc: 0.5267 - val_loss: 0.9679 - val_acc: 0.5399
Epoch 4/1000


KeyboardInterrupt: 

In [8]:
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model.h5")
print("Saved model to disk")

Saved model to disk


In [2]:
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")
loaded_model.summary()

Loaded model from disk
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv1 (Conv2D)               (None, 224, 224, 32)      896       
_________________________________________________________________
relu1 (Activation)           (None, 224, 224, 32)      0         
_________________________________________________________________
maxpool1 (MaxPooling2D)      (None, 223, 223, 32)      0         
_________________________________________________________________
conv2 (Conv2D)               (None, 223, 223, 64)      18496     
_________________________________________________________________
relu2 (Activation)           (None, 223, 223, 64)      0         
_________________________________________________________________
maxpool2 (MaxPooling2D)      (None, 111, 111, 64)      0         
_________________________________________________________________
conv3 (Conv2D)               (None, 111, 111, 128)   

In [10]:
#this doesnt work to reset
from keras import backend as K

def limit_mem():
    K.get_session().close()
    cfg = K.tf.ConfigProto()
    cfg.gpu_options.allow_growth = True
    K.set_session(K.tf.Session(config=cfg))

limit_mem()

In [6]:

predict = loaded_model.predict(X_test)

In [8]:
predict[0]


array([  1.00749046e-13,   1.00000000e+00,   2.02010197e-11], dtype=float32)